INSERT INTO "artists" ("name") VALUES
('Aaron Dessner'),
('Max Martin'),
('Shellback'),
('Louis Bell'),
('Frank Dukes'),
('Liz Rose'),
('Tom Petty'),
('Jack Antonoff'),
('Patrick Monahan'),
('Kendrick Lamar'),
('Andrew Lloyd Webber'),
('Donna Weiss'),
('Jackie DeShannon'),
('William Bowery'),
('Stephony Smith'),
('Bobby Ray Simmons, Jr.'),
('Ammar Malik'),
('Lukasz Gottwald'),
('Henry Walter'),
('Colbie Caillat'),
('Kevin Griffin'),
('Nathan Chapman'),
('Imogen Heap'),
('Dan Wilson'),
('Robert Ellis Orrall'),
('St. Vincent'),
('Oscar Holter'),
('Charlie Colin'),
('Rob Hotchkiss'),
('Jimmy Stafford'),
('Pat Monahan'),
('Scott Underwood'),
('Ed Sheeran'),
('Nayvadius Wilburn'),
('Justin Vernon'),
('Hillary Lindsey'),
('John Mayer'),
('Mark Irwin'),
('Josh Kear'),
('Brad Warren'),
('Brett Warren'),
('Blu Sanders'),
('Sam Dew'),
('Ryan Tedder'),
('Freddie Perren'),
('Deke Richards'),
('Berry Gordy, Jr.'),
('Alphonso Mizell'),
('Martin Johnson'),
('Angelo Petraglia'),
('TBA'),
('George Michael'),
('Gary Lightbody'),
('Jacknife Lee'),
('Paula Fernandes'),
('Cautious Clay'),
('Sounwave'),
('Fred Fairbrass'),
('Richard Fairbrass'),
('Rob Manzoli[d]'),
('Shawn Mendes'),
('Scott Harris'),
('T. S. Eliot'),
('Joel Little'),
('Brian Maher'),
('Brendon Urie'),
('Brett James'),
('Troy Verges'),
('Ali Payami'),
('Maya Thompson'),
('Joy Williams'),
('John Paul White'),
('T-Bone Burnett'),
('Joan Javits'),
('Philip Springer'),
('Tony Springer'),
('Maurice White'),
('Al McKay'),
('Allee Willis'),
('Josef Mohr'),
('Franz Xaver Gruber'),
('Oscar Görres'),
('Christopher Tricky Stewart'),
('Terius Dream Nash'),
('Thaddis Harrell'),
('Shawn Carter'),
('Cary Barlowe'),
('Nathan Barlowe'),
('Tommy Lee James'),
('Taylor Swift[g]'),
('John Rich'),
('Irving Berlin'),
('Taylor Swift'),
('Sugarland'),
('Kenny Chesney'),
('B.o.B'),
('Tim McGraw'),
('Jack Ingram'),
('Zayn'),
('Boys Like Girls');
