INSERT INTO "albums" ("title") VALUES
('Fearless (Platinum edition) and Valentine''s Day: Soundtrack'),
('Folklore'),
('Red'),
('Lover'),
('1989'),
('None[a]'),
('Bigger'),
('Speak Now'),
('None[b]'),
('Beautiful Eyes'),
('Cats: Highlights from the Motion Picture Soundtrack'),
('Fearless'),
('Speak Now World Tour – Live'),
('Live in No Shoes Nation'),
('Strange Clouds'),
('Hope for Haiti Now'),
('Reputation'),
('AT&T Team USA Soundtrack and Fearless'),
('Sounds of the Season'),
('None'),
('Taylor Swift'),
('Red (Deluxe edition)'),
('Fearless (Platinum edition)'),
('Hannah Montana: The Movie'),
('The Hunger Games'),
('Battle Studies'),
('Two Lanes of Freedom'),
('Rhapsody Originals[c]'),
('Fifty Shades Darker: Original Motion Picture Soundtrack'),
('Speak Now (Deluxe edition)'),
('Taylor Swift (Deluxe edition)'),
('Folklore (Physical Edition)'),
('None[e]'),
('1989 (Deluxe edition)'),
('Spotify Singles'),
('One Chance Soundtrack'),
('Valentine''s Day[f]'),
('Love Drunk'),
('iTunes Live from SoHo');
